### PR TITLE
Optimize game/item random

### PR DESCRIPTION
**Pull request by serprex**
Might need a using on some traits, I'm still a bit new with Rust & can't build because this depends on unstable

### CODE REVIEW

**Comment by dpc** [comment]
Please see: https://travis-ci.org/dpc/rhex/jobs/103865815

Something is missing `use <the trait you're trying to use>` I believe. I advise you to install "multirust", then run `multirust default nightly` if that what you mean by problems with unstable.

And thanks for PR! I'm actively looking for people interested in working on rhex. :)

**Comment by serprex** [comment]
I've committed a fix

It may be wise to use stable if you're seeking contributors

**Comment by dpc** [comment]
You're right. #6

**Comment by dpc** [comment]
Thank you for fix!

**Pull request merged**
